FROM node:alpine

RUN mkdir -p /home/node/app/node_modules
WORKDIR /home/node/app
COPY package*.json /home/node/app/

RUN npm install -g @angular/cli

RUN npm install
COPY --chown=node:node . .
EXPOSE 4200
CMD ["ng", "serve", "--host", "0.0.0.0"]