FROM node:hydrogen-alpine
RUN mkdir -p /home/node/app/node_modules
WORKDIR /home/node/app
COPY package*.json /home/node/app/

RUN npm install
COPY --chown=node:node . .
EXPOSE 8080

CMD [ "node", "index.js" ]